[project]
name = "inctxdt"
description = ""
requires-python = ">=3.10"
version = "0.0.1"

[build-system]
requires = ["setuptools>=68.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["inctxdt"]
